services:
  - type: web
    name: raincrm
    env: ruby
    plan: free
    buildCommand: bundle install --deployment && bundle exec rails tailwindcss:build && bundle exec rails assets:precompile && bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RUBY_VERSION
        value: 3.2.2
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: raincrm-db
          property: connectionString
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: raincrm-db
    plan: free